//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_13.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        [Key]
        public int CId { get; set; }
        public string CName { get; set; }
       public Nullable<double> CFee { get; set; }

        public string Technology { get; set; }
        public  string Status { get; set; }
    }
}
